### ISSUE TITLE
No icon on desktop and not searchable

### ISSUE THREAD

**Issue by Anitalex** [flcdrg/au-packages#67]
This does not place an icon on the desktop and is not searchable on the start menu. You have to go to C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Teams\Programs\Microsoft Corporation\ to get the shortcut and then place it on the public desktop

**Comment by flcdrg** [comment]
Can you confirm if this in relation to https://chocolatey.org/packages/microsoft-teams or https://chocolatey.org/packages/microsoft-teams.install?

**Comment by Anitalex** [comment]
It happened with both.  I had to copy the executable to the public desktop and public start menu


Thanks,

Carlos McCray
Director, Service Delivery

ProviDyn, Inc.
6065 Roswell  Road, Suite 150
Atlanta, GA 30328

Support: 404.920.8650
Direct:  404.551.5492 ext 540
Fax: 404.551.5630

carlos.mccray@providyn.com
www.ProviDyn.com

Driving Business Through Technology


________________________________

**Comment by flcdrg** [comment]
It might be possible to add a desktop shortcut as part of the install script for the `microsoft-team` package.

The MSI package (`microsoft-teams.install`) operates differently - it just puts the MSI in place so that when each user logs in to the machine, the installer then runs individually for them. See https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment#how-the-microsoft-teams-msi-package-works for more info.

**Comment by Anitalex** [comment]
Ok got it.  I added lines to my script to copy the Microsoft Teams file in the C:\Windows\SysWoW64 \..\.... folder to public desktop and start menu so that should be good enough to have something for people to click.  There's just no way users are going to find that file


Thanks,

Carlos McCray
Director, Service Delivery

ProviDyn, Inc.
6065 Roswell  Road, Suite 150
Atlanta, GA 30328

Support: 404.920.8650
Direct:  404.551.5492 ext 540
Fax: 404.551.5630

carlos.mccray@providyn.com
www.ProviDyn.com

Driving Business Through Technology


________________________________
